### ISSUE TITLE
Window behavior

### ISSUE THREAD

**Issue by AlexanderKaschta** [PhyPiDAQ/PhyPiDAQ#7]
Resize the main window correctly and space out the components equally.

**Comment by uadlq** [comment]
made a pull request to fix this issue.

**Comment by AlexanderKaschta** [comment]
I've created a merge request addressing th resizing of the plot display and its lagging notification. The merge request can be found under: #10

**Comment by AlexanderKaschta** [comment]
TODO (including suggestions from @uadlq):

- [ ] Add LayoutManagers to the MainWindow, to enable features like resizing.
  - [ ] Give the `self.centralwidget` a layout
  - [ ] Remove parent layouts and migrate them to a layout
  - [ ] Remove size properties of elements, that should resize
- [ ] Remove unnecessary HTML-Code from the tooltips, to provide a better user experience, as they behave much better considering their text flow behavior.
- [ ] Get rid of the *.ui-file? This seems like a radical idea, but it's hard to maintain changes and comments to the UI-class while giving everybody the possibility to simply override those changes by parsing the file again. Additionally the `Display.py`-class is currently also implemented only using code.

**Comment by AlexanderKaschta** [comment]
Initial draft of the fix can be found in the commit https://github.com/PhyPiDAQ/PhyPiDAQ/commit/17d17e0c35ca5eb52853cecf7157f1d97ea6cd17.

**Comment by AlexanderKaschta** [comment]
This should be fixed.
